/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\Users\kslabig\Desktop\gb\gbtd\golf_bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapWidth 32
#define MapHeight 32
#define MapBank 0

extern unsigned char Map[];

/* End of MAP.H */
