/*

 WIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : Z:\Users\kslabig\Desktop\gb\gbtd\golf_bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WinWidth 20
#define WinHeight 3
#define WinBank 0

extern unsigned char Win[];

/* End of WIN.H */
